name: Setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - name: Install Turbo CLI
      shell: bash
      run: pnpm add --global turbo
    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install
    - name: Setup Xcode
      if: runner.os == 'macOS'
      shell: bash
      run: |
        sudo xcode-select --switch "$(find /Applications/ -maxdepth 1 -name 'Xcode*.app' | sort -V | tail -n 1)"
        xcodebuild -version
