packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.35.0
  prettier: ^3.6.2
  typescript: ~5.9.2

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ~19.1.10
    '@types/react-dom': ^19.1.0

ignoredBuiltDependencies:
  - unrs-resolver
  - supabase

nodeLinker: hoisted

onlyBuiltDependencies:
  - core-js-pure
  - supabase
