name: Backend Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - production
          - preview
  workflow_call:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: string

defaults:
  run:
    working-directory: 'apps/backend'

concurrency:
  cancel-in-progress: true
  group: ${{ inputs.environment }}-backend-deploy

jobs:
  build-vercel:
    name: Build Vercel
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm add --global vercel
      - run: vercel link --repo --yes --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel pull --environment ${{ inputs.environment }} --yes --token ${{ secrets.VERCEL_TOKEN }}
      - run: turbo build:vercel -- --target ${{ inputs.environment }} --token ${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --target ${{ inputs.environment }} --prebuilt --archive tgz --token ${{ secrets.VERCEL_TOKEN }}
