name: Mobile Check

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: 'apps/mobile'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: turbo run lint:check

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: turbo run format:check -- .

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: turbo run build:check

  expo:
    name: Expo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm exec expo install --check
      - run: pnpx expo-doctor@1.15.1
