name: Supabase

on:
  push:
    paths:
      - 'packages/supabase/**'
      - '.github/**'

jobs:
  check:
    name: Check
    uses: ./.github/workflows/supabase-check.yml

  production-deploy:
    name: Production Deploy
    if: github.ref == 'refs/heads/main'
    needs: [check]
    uses: ./.github/workflows/supabase-deploy.yml
    secrets: inherit
    with:
      environment: production

  staging-deploy:
    name: Staging Deploy
    if: github.ref == 'refs/heads/staging'
    needs: [check]
    uses: ./.github/workflows/supabase-deploy.yml
    secrets: inherit
    with:
      environment: preview
